### ISSUE TITLE
Add dependency version checking badge

### ISSUE THREAD

**Issue by paazmaya** [matthiasnoback/microsoft-translator#12]
https://gemnasium.com/ or http://www.versioneye.com/ make it easy to see which dependencies are out of date.

**Comment by matthiasnoback** [comment]
Sorry, running out of time :)

**Comment by paazmaya** [comment]
Could I help with this?
It would simply require to login in one of those services, import a list of GitHub repositories and choosing this one to be tracked.
It would then show a markdown syntax link to be added in the `README.md`.

**Comment by matthiasnoback** [comment]
Alright, if you insist ;) Done.

I don't really care much about this library anymore. Are you interested in taking over maintenance?

**Comment by paazmaya** [comment]
Umm... I am afraid to say yes, as I fear to having not enough time for it.

**Comment by paazmaya** [comment]
Anyhow, thank you for adding the badge and asking for maintaining

**Comment by matthiasnoback** [comment]
No problem :)
