### ISSUE TITLE
Request Failed

### ISSUE THREAD

**Issue by dhrubo001** [matthiasnoback/microsoft-translator#14]
I just using this package have given in client id and secret but when i am translating its said REQUEST FAILED

**Comment by matthiasnoback** [comment]
Please provide a full dump of the exception, including previous exceptions (just catch the exception and echo it).

**Comment by dhrubo001** [comment]
This is the issue i am facing..
![error](https://cloud.githubusercontent.com/assets/7116995/12171047/826ce46e-b56c-11e5-957b-b73ed3de850f.png)

**Comment by dhrubo001** [comment]
I can't understand what's the problem..please help

**Comment by matthiasnoback** [comment]
I don't know what that means. It seems a PHP error from file_get_contents. You should try to use a different Buzz client, e.g. use the Curl client.

**Comment by dhrubo001** [comment]
Actually i am using laravel 4.2..is it bcoz of this or something else....it's not echoing the error too

**Comment by dhrubo001** [comment]
Can u give me  example code or something

**Comment by matthiasnoback** [comment]
Do something like this:
```
$client = new Curl();
$browser = new Browser($client);
```
Then see what exception gets thrown.

**Comment by dhrubo001** [comment]
Nothing hapenning bro???

**Comment by matthiasnoback** [comment]
Did you use this `$browser` object to make actual requests to the API?

**Comment by nagyszem22** [comment]
I have got the same issue with Laravel 5.2, I have no idea what to do, it seems like my id or my secret is not correct so the authentication process fails. But they are correct I think. This is what worries me:
![image](https://cloud.githubusercontent.com/assets/6263869/15627756/68128a6e-24ee-11e6-9905-b8a5d4c34b85.png)

It is from the translator page I subscribed in azure market. The problem can be caused because this is v1?

**Comment by matthiasnoback** [comment]
Sorry guys, I have no recent experience with MicrosoftTranslator at all. There's no guarantees whatsoever that it still works. So: please debug some more. If the exception isn't clear, dump it, or better: use Xdebug to step through until you get to the problem. Also, switch to Curl, etc.

**Comment by ahmedash95** [comment]
@matthiasnoback there is something weird about this exception .. it works good at localhost but on the server it gives me this exception ``` exception 'Buzz\Exception\RequestException' ```

```
#0 my_project_path/vendor/kriswallsmith/buzz/lib/Buzz/Browser.php(130): Buzz\Client\FileGetContents->send(Object(Buzz\Message\Request), Object(Buzz\Message\Response))
#1 my_project_path/vendor/kriswallsmith/buzz/lib/Buzz/Browser.php(82): Buzz\Browser->send(Object(Buzz\Message\Request))
#2 my_project_path/vendor/kriswallsmith/buzz/lib/Buzz/Browser.php(36): Buzz\Browser->call('https://datamar...', 'POST', Array, 'client_id=3d669...')
#3 my_project_path/vendor/matthiasnoback/microsoft-translator/src/MatthiasNoback/MicrosoftOAuth/AccessTokenProvider.php(83): Buzz\Browser->post('https://datamar...', Array, 'client_id=3d669...')
#4 my_project_path/vendor/matthiasnoback/microsoft-translator/src/MatthiasNoback/MicrosoftOAuth/AccessTokenProvider.php(60): MatthiasNoback\MicrosoftOAuth\AccessTokenProvider->authorize('http://api.micr...', 'client_credenti...')
#5 my_project_path/vendor/matthiasnoback/microsoft-translator/src/MatthiasNoback/MicrosoftTranslator/MicrosoftTranslator.php(227): MatthiasNoback\MicrosoftOAuth\AccessTokenProvider->getAccessToken('http://api.micr...', 'client_credenti...')
#6 my_project_path/vendor/matthiasnoback/microsoft-translator/src/MatthiasNoback/MicrosoftTranslator/MicrosoftTranslator.php(195): MatthiasNoback\MicrosoftTranslator\MicrosoftTranslator->getAccessToken()
#7 my_project_path/vendor/matthiasnoback/microsoft-translator/src/MatthiasNoback/MicrosoftTranslator/MicrosoftTranslator.php(141): MatthiasNoback\MicrosoftTranslator\MicrosoftTranslator->call(Object(MatthiasNoback\MicrosoftTranslator\ApiCall\Speak))
#8 my_project_path/app/Services/TextToSpeach.php(25): MatthiasNoback\MicrosoftTranslator\MicrosoftTranslator->speak('' ?????????????...', 'ar', 'audio/mp3', 'MaxQuality')
#9 my_project_path/app/Http/Controllers/VideosController.php(9): App\Services\TextToSpeach->text('' ?????????????...', '/var/www/html/l...')
#10 my_project_path/app/Console/Commands/NewsRandomeVideoPublisher.php(46): App\Http\Controllers\VideosController->generateFromRaw(Object(App\News))
#11 [internal function]: App\Console\Commands\NewsRandomeVideoPublisher->handle()
#12 my_project_path/vendor/laravel/framework/src/Illuminate/Container/Container.php(507): call_user_func_array(Array, Array)
#13 my_project_path/vendor/laravel/framework/src/Illuminate/Console/Command.php(169): Illuminate\Container\Container->call(Array)
#14 my_project_path/vendor/symfony/console/Command/Command.php(256): Illuminate\Console\Command->execute(Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
#15 my_project_path/vendor/laravel/framework/src/Illuminate/Console/Command.php(155): Symfony\Component\Console\Command\Command->run(Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
#16 my_project_path/vendor/symfony/console/Application.php(791): Illuminate\Console\Command->run(Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
```

**Comment by matthiasnoback** [comment]
Ah, usually this has something to do with SSL - something about a difference in server time maybe, or the list of accepted certificate authorities, etc. You should definitely not use FileGetContents anyway, try Curl instead, which gives much more detailed error messages anyway.

**Comment by ahmedash95** [comment]
@matthiasnoback , after installing ssl and using curl insted of FileGetContnets it still gives me ``` API call was not successful, 400: Bad Request ``` . somtimes it works and somtimes throws this exception .. i tried to figure out what happen but i don't found it yet.

**Comment by matthiasnoback** [comment]
I'm sorry people, there's nothing I can do here.

**Comment by ghprod** [comment]
make sure you already subscribe to `datamarket.azure.com/dataset/bing/microsofttranslator` also your current balance is not zero ..thats it :)
