### ISSUE TITLE
file_get_contents - failed to open stream

### ISSUE THREAD

**Issue by raivisdejus** [matthiasnoback/microsoft-translator#16]
Hi,

I get the following error on one of my servers. It is shared hosting. Everything is fine on my local dev server.

<b>Fatal error</b>:  Uncaught exception 'Buzz\Exception\RequestException' with message 'file_get_contents(https://datamarket.accesscontrol.windows.net/v2/OAuth2-13): failed to open stream: operation failed' in /home/site/public_html/vendor/kriswallsmith/buzz/lib/Buzz/Client/FileGetContents.php:28

allow_url_fopen is enabled

Any ideas?

**Comment by matthiasnoback** [comment]
This has been answered in various older issues ;) In short; nothing I can do about this. Just switch to Curl.

**Comment by raivisdejus** [comment]
Thanks, I found the necessary in one of the older issues.
