### ISSUE TITLE
Ambiguous class resolution warning

### ISSUE THREAD

**Issue by rogervila** [matthiasnoback/microsoft-translator#21]
Hello,

On a Laravel project, I included the v3 beta release on my `composer.json` file

```json
{
    "matthiasnoback/microsoft-translator": "v3.0-beta"
}
```

After running `composer update`, I get this message:

```
Warning: Ambiguous class resolution, "MatthiasNoback\MicrosoftTranslator\ApiCall\GetLanguagesForTranslate" was found in both "/var/www/vendor/matthiasnoback/microsoft-translator/src/MatthiasNoback/MicrosoftTranslator/ApiCall/GetLanguages.php" and "/var/www/vendor/matthiasnoback/microsoft-translator/src/MatthiasNoback/MicrosoftTranslator/ApiCall/GetLanguagesForTranslate.php", the first will be used.
```

If I am not the only one that gets this message, I can work on a PR that fixes it.

Thank you.

**Comment by arraintxo** [comment]
That was an unused file (not sure what I was thinking about when I created it) so I removed it again. Should be fine now.

Published a new beta release with this change.
Thank you for your feedback.

**Comment by rogervila** [comment]
Thank you @arraintxo
