### ISSUE TITLE
Update library description

### ISSUE THREAD

**Issue by arraintxo** [matthiasnoback/microsoft-translator#23]
Hi Matthias,

could you please update repository's description to "PHP library for making calls to the Microsoft Translator Text API (V3)", it still says that it calls to V2 version when it doesn't anymore.

Sorry, I'm not able to modify this.

**Comment by matthiasnoback** [comment]
Ah, no problem, I've just changed it!

**Comment by arraintxo** [comment]
That was fast @matthiasnoback, thank you!
