### ISSUE TITLE
Laravel 8

### ISSUE THREAD

**Issue by sheinfeld** [matthiasnoback/microsoft-translator#24]
Hi there,

Could you add support to Laravel 8?

Thank you!

**Comment by arraintxo** [comment]
Did you have any trouble with it? This is a framework agnostic package, so it should be compatible with Laravel 8. 

If what you want is a Laravel package, it isn't this libraries purpose to provide such functionality. But it shouldn't be too difficult to create a package on your own if you really need this.

Personally I would register/initialize the MicrosoftTranslator in the AppServiceProvider to be able to inject it anywhere in my app, without any need of additional packages. That's basically what the package would do.

Something similar to this should work (didn't test it). You could have the azureKey inside config/translator.php
```
// AppServiceProvider.php
public function register()
{
         $this->app->singleton(MicrosoftTranslator::class, function ($app) {
                  $browser = new Browser();
                  $azureKey = config('translator.azureKey');
                  $accessTokenProvider = new AzureTokenProvider($browser, $azureKey);
                  $translator = new MicrosoftTranslator($browser, $accessTokenProvider);
        });
}
```

**Comment by sheinfeld** [comment]
Hi @arraintxo,

I just realised that apologies...

My problem is actually when I add it to composer, it seams it uses outdated libraries and It just rollback :(

Anyways, great job with the package, thank you!

**Comment by arraintxo** [comment]
I guess we should update some library dependencies then. 
Thanks for your feedback, I will take a look as soon as possible.
