### ISSUE TITLE
PHP v 8.x issue

### ISSUE THREAD

**Issue by sscotti** [matthiasnoback/microsoft-translator#26]
Trying to update my packages and wondering how to resolve this:

  Problem 1
    - kriswallsmith/buzz v0.16.1 requires php ^5.4 || ^7.0 -> your php version (8.0.9) does not satisfy that requirement.
    - matthiasnoback/microsoft-translator dev-master requires kriswallsmith/buzz ^0.16.1 -> satisfiable by kriswallsmith/buzz[v0.16.1].
    - Root composer.json requires matthiasnoback/microsoft-translator dev-master -> satisfiable by matthiasnoback/microsoft-translator[dev-master].

**Comment by saschati** [comment]
Maybe need to create a fork?

**Comment by sscotti** [comment]
Maybe.  I frankly don't use the package that much anymore, but it would be nice to have it be compatible with php version 8.

**Comment by arraintxo** [comment]
Sorry for the delay, I've been busy the last month and didn't realize about this issue. 
But I will sure take a look to this.

**Comment by arraintxo** [comment]
I started working on this. 

You can see some advancements on php8 branch if you want: 
https://github.com/matthiasnoback/microsoft-translator/tree/php8

Everything seems to work properly as far as we don't use cache functionality. I will try to fix that ASAP too.

There are be some bc breaks as Buzz browser has changed a lot from 0.16 version (as expected). 
I guess we'll also have to release a new major version after everything is working.

**Comment by arraintxo** [comment]
I have just released v4.0-beta version with PHP8.0 support.
Hope everything works OK.

Take into account Cache and Buzz browser related changes while upgrading.
